importing multiclient's account(s)
stereum-dev/ethereum2-ansible pull request #37
Opened 2021-03-23 19:51 UTC by gbayasgalan

2021-03-23 20:02 UTC, stefa2k requested changes

2021-03-23 20:27 UTC, gbayasgalan commented on roles/import-validator-keys-multiclient/tasks/main.yaml
> +- name: Add ethdo to PATH
task - "Add ethdo to PATH" is removed

2021-03-23 20:28 UTC, gbayasgalan commented on roles/import-validator-keys-multiclient/tasks/main.yaml
> +  shell: ~/go/bin/ethdo wallet create --type=hd --mnemonic="{{validator_mnemonic}}" --wallet="Wallet" --wallet-passphrase="StereumP@ssw0rd"
wallet passphrase is generated automatically

2021-03-23 20:56 UTC, gbayasgalan commented on roles/import-validator-keys-multiclient/tasks/main.yaml
> +    ~/go/bin/ethdo account create --account="Wallet/Account-$i" --path=m/12381/3600/$i/0/0 --wallet-passphrase="StereumP@ssw0rd" --passphrase="{{validator_password}}"  --allow-weak-passphrases
now, wallet and account will use same passphrase(auto generated)

2021-03-24 08:20 UTC, stefa2k requested changes

2021-03-24 08:20 UTC, stefa2k commented on roles/import-validator-keys-multiclient/tasks/main.yaml
> +    content: 'StereumP@ssw0rd'
Should use `{{ validator_password }}` I think

2021-03-24 08:42 UTC, stefa2k approved these changes
lgtm

2021-03-24 08:42 UTC, merged